name: Free RDP with Ngrok
on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Setup RDP User
        run: |
          net user riyan saputra /add
          net localgroup administrators riyan /add
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          reg add "HKLM\SYSTEM\CurrentControlSet\Services\TermService" /v Start /t REG_DWORD /d 2 /f
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v PortNumber /t REG_DWORD /d 3389 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          netsh advfirewall firewall set rule group="Remote Desktop" new enable=Yes

      - name: Install Latest Ngrok
        run: |
          Write-Output "🛠️ Installing the latest Ngrok version..."
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath $env:USERPROFILE

      - name: Check Ngrok Version
        run: |
          Write-Output "🔍 Checking Ngrok version..."
          & $env:USERPROFILE\ngrok.exe version

      - name: Authenticate Ngrok (Auto Token)
        run: |
          Write-Output "🔑 Authenticating Ngrok..."
          & $env:USERPROFILE\ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Start Ngrok Tunnel
        run: |
          Write-Output "🚀 Starting Ngrok Tunnel..."
          Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok.exe" -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 15  # Tunggu agar Ngrok siap

      - name: Get Ngrok URL
        run: |
          Write-Output "🌐 Retrieving Ngrok Public Address..."
          Start-Sleep -Seconds 5  # Tambahkan delay sebelum mengambil URL
          $ngrok_info = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"
          $ngrok_url = $ngrok_info.tunnels[0].public_url
          Write-Output "🔗 Connect to RDP via: $ngrok_url"
