name: Free VNC with UltraVNC & Ngrok
on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Download UltraVNC Installer
        run: |
          Write-Output "🛠️ Downloading UltraVNC Installer..."
          Invoke-WebRequest -Uri "https://www.uvnc.eu/download/UltraVNC_1_3_8_X64_Setup.msi" -OutFile ultravnc.msi

      - name: Install UltraVNC
        run: |
          Write-Output "🛠️ Installing UltraVNC Server..."
          Start-Process msiexec.exe -ArgumentList "/i ultravnc.msi /quiet /norestart" -Wait

      - name: Set UltraVNC Password
        run: |
          Write-Output "🔑 Setting UltraVNC Password..."
          $password = "saputra"
          $regPath = "HKLM:\Software\UltraVNC"
          New-Item -Path $regPath -Force
          Set-ItemProperty -Path $regPath -Name "passwd" -Value ([System.Text.Encoding]::ASCII.GetBytes($password) | ForEach-Object { $_ -bxor 123 })

      - name: Start UltraVNC Server
        run: |
          Write-Output "🚀 Starting UltraVNC Server..."
          Start-Process "C:\Program Files\uvnc bvba\UltraVNC\winvnc.exe"

      - name: Install Latest Ngrok
        run: |
          Write-Output "🛠️ Installing the latest Ngrok version..."
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath $env:USERPROFILE

      - name: Authenticate Ngrok
        run: |
          Write-Output "🔑 Authenticating Ngrok..."
          & $env:USERPROFILE\ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Start Ngrok Tunnel
        run: |
          Write-Output "🚀 Starting Ngrok Tunnel for VNC..."
          Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok.exe" -ArgumentList "tcp 5900"
          Start-Sleep -Seconds 30

      - name: Get Ngrok URL
        run: |
          Write-Output "🌐 Retrieving Ngrok Public Address..."
          Start-Sleep -Seconds 10
          $ngrok_info = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -ErrorAction Stop
          $ngrok_url = $ngrok_info.tunnels[0].public_url
          Write-Output "🔗 Connect to VNC via: $ngrok_url"
