- name: Install UltraVNC
  run: |
    Write-Output "🛠️ Installing UltraVNC Server..."
    $installerPath = "$env:USERPROFILE\ultravnc.msi"
    
    # Coba download UltraVNC jika belum ada
    if (-not (Test-Path $installerPath)) {
        Write-Output "🔽 Downloading UltraVNC Installer..."
        Invoke-WebRequest -Uri "https://uvnc.com/downloads/UltraVNC_1_3_81_Setup.exe" -OutFile $installerPath -UseBasicParsing
    }

    # Install UltraVNC secara silent
    Start-Process msiexec.exe -ArgumentList "/i $installerPath /quiet /norestart" -Wait
    Write-Output "✅ UltraVNC Installed!"

- name: Verify UltraVNC Installation
  run: |
    Write-Output "🔎 Verifying UltraVNC Installation..."
    $uvncPath1 = "C:\Program Files\uvnc bvba\UltraVNC\winvnc.exe"
    $uvncPath2 = "C:\Program Files (x86)\uvnc bvba\UltraVNC\winvnc.exe"

    if (Test-Path $uvncPath1) {
        Write-Output "✅ UltraVNC found at $uvncPath1"
    } elseif (Test-Path $uvncPath2) {
        Write-Output "✅ UltraVNC found at $uvncPath2"
    } else {
        Write-Output "❌ UltraVNC installation failed!"
        exit 1
    }

- name: Start UltraVNC Server
  run: |
    Write-Output "🚀 Starting UltraVNC Server..."
    $uvncPath1 = "C:\Program Files\uvnc bvba\UltraVNC\winvnc.exe"
    $uvncPath2 = "C:\Program Files (x86)\uvnc bvba\UltraVNC\winvnc.exe"

    if (Test-Path $uvncPath1) {
        Start-Process -NoNewWindow -FilePath $uvncPath1
    } elseif (Test-Path $uvncPath2) {
        Start-Process -NoNewWindow -FilePath $uvncPath2
    } else {
        Write-Output "❌ UltraVNC executable not found!"
        exit 1
    }
    Write-Output "✅ UltraVNC Server Started!"
    
