name: Free RDP
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          net user riyan saputra /add
          net localgroup administrators riyan /add
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          netsh advfirewall firewall set rule group="Remote Desktop" new enable=Yes
