name: Free VNC with Ngrok
on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install TightVNC Server
        run: |
          Write-Output "🛠️ Installing TightVNC Server..."
          Invoke-WebRequest -Uri "https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-setup-64bit.msi" -OutFile tightvnc.msi
          Start-Process msiexec.exe -ArgumentList "/i tightvnc.msi /quiet /norestart" -Wait

      - name: Configure TightVNC Password
        run: |
          Write-Output "🔑 Setting TightVNC Password..."
          $password = "saputra"
          $registryPath = "HKLM:\Software\TightVNC\Server"
          New-Item -Path $registryPath -Force
          Set-ItemProperty -Path $registryPath -Name "Password" -Value ([System.Text.Encoding]::ASCII.GetBytes($password) | ForEach-Object { $_ -bxor 123 })
          Set-ItemProperty -Path $registryPath -Name "AcceptRFBConnections" -Value 1
          Set-ItemProperty -Path $registryPath -Name "LocalLoopback" -Value 0
          Set-ItemProperty -Path $registryPath -Name "AlwaysShared" -Value 1
          Set-ItemProperty -Path $registryPath -Name "AllowLoopback" -Value 1
          Set-ItemProperty -Path $registryPath -Name "RfbPort" -Value 5900
          Start-Process "C:\Program Files\TightVNC\tvnserver.exe"

      - name: Install Latest Ngrok
        run: |
          Write-Output "🛠️ Installing the latest Ngrok version..."
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath $env:USERPROFILE

      - name: Authenticate Ngrok (Auto Token)
        run: |
          Write-Output "🔑 Authenticating Ngrok..."
          & $env:USERPROFILE\ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Start Ngrok Tunnel in Background
        run: |
          Write-Output "🚀 Starting Ngrok Tunnel for VNC..."
          Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok.exe" -ArgumentList "tcp 5900"
          Start-Sleep -Seconds 30  # Tunggu agar Ngrok siap

      - name: Get Ngrok URL
        run: |
          Write-Output "🌐 Retrieving Ngrok Public Address..."
          Start-Sleep -Seconds 10
          $ngrok_info = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -ErrorAction Stop
          $ngrok_url = $ngrok_info.tunnels[0].public_url
          Write-Output "🔗 Connect to VNC via: $ngrok_url"
