name: Free VNC with UltraVNC & Ngrok
on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install UltraVNC Server
        run: |
          Write-Output "🛠️ Installing UltraVNC Server..."
          Invoke-WebRequest -Uri "https://uvnc.com/downloads/ultravnc/132-ultravnc-1-3-81.html" -OutFile ultravnc.exe
          Start-Process ultravnc.exe -ArgumentList "/silent /verysilent /norestart" -Wait

      - name: Configure UltraVNC Password
        run: |
          Write-Output "🔑 Setting UltraVNC Password..."
          $password = "saputra"
          $regPath = "HKLM:\Software\ORL\WinVNC3"
          New-Item -Path $regPath -Force
          Set-ItemProperty -Path $regPath -Name "Password" -Value ([System.Text.Encoding]::ASCII.GetBytes($password) | ForEach-Object { $_ -bxor 123 })
          Start-Process "C:\Program Files\UltraVNC\winvnc.exe"

      - name: Install Latest Ngrok
        run: |
          Write-Output "🛠️ Installing the latest Ngrok version..."
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath $env:USERPROFILE

      - name: Authenticate Ngrok (Auto Token)
        run: |
          Write-Output "🔑 Authenticating Ngrok..."
          & $env:USERPROFILE\ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Start Ngrok Tunnel in Background
        run: |
          Write-Output "🚀 Starting Ngrok Tunnel for VNC..."
          Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok.exe" -ArgumentList "tcp 5900"
          Start-Sleep -Seconds 30  # Tunggu agar Ngrok siap

      - name: Get Ngrok URL
        run: |
          Write-Output "🌐 Retrieving Ngrok Public Address..."
          Start-Sleep -Seconds 10
          $ngrok_info = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -ErrorAction Stop
          $ngrok_url = $ngrok_info.tunnels[0].public_url
          Write-Output "🔗 Connect to VNC via: $ngrok_url"
